/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
          "on-primary-container": "#005b2b",
          "on-primary": "#006530",
          "primary-dim": "#00ed7b",
          "surface-container": "#181a19",
          "background": "#0d0f0e",
          "secondary-dim": "#679dff",
          "primary": "#a5ffb8",
          "inverse-primary": "#006e36",
          "tertiary-dim": "#ff734a",
          "tertiary-container": "#ff5722",
          "on-error-container": "#ffa8a3",
          "on-tertiary-fixed": "#340800",
          "on-surface-variant": "#aaaba9",
          "on-secondary-fixed": "#003270",
          "tertiary": "#ff734a",
          "on-primary-fixed": "#004620",
          "surface": "#0d0f0e",
          "on-tertiary-container": "#250400",
          "on-background": "#f7f6f4",
          "error": "#ff716c",
          "surface-dim": "#0d0f0e",
          "on-primary-fixed-variant": "#006631",
          "on-tertiary": "#430c00",
          "on-surface": "#f7f6f4",
          "on-error": "#490006",
          "surface-variant": "#242625",
          "surface-container-highest": "#242625",
          "secondary-container": "#005bc0",
          "outline-variant": "#474847",
          "outline": "#747674",
          "inverse-surface": "#faf9f7",
          "on-tertiary-fixed-variant": "#6f1a00",
          "surface-tint": "#a5ffb8",
          "primary-container": "#00fd84",
          "error-container": "#9f0519",
          "error-dim": "#d7383b",
          "secondary": "#679dff",
          "inverse-on-surface": "#545554",
          "on-secondary": "#001f49",
          "on-secondary-fixed-variant": "#004ea6",
          "surface-container-high": "#1e201f",
          "tertiary-fixed": "#ff9475",
          "surface-container-low": "#121413",
          "primary-fixed-dim": "#00ed7b",
          "primary-fixed": "#00fd84",
          "tertiary-fixed-dim": "#ff7d57",
          "secondary-fixed-dim": "#a8c4ff",
          "surface-bright": "#2a2d2b",
          "secondary-fixed": "#bed2ff",
          "surface-container-lowest": "#000000",
          "on-secondary-container": "#f7f7ff"
      },
      borderRadius: {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "1.5rem",
          "full": "9999px"
      },
      fontFamily: {
          headline: ["Lexend", "sans-serif"],
          body: ["Plus Jakarta Sans", "sans-serif"],
          label: ["Lexend", "sans-serif"]
      }
    },
  },
  plugins: [],
}
